package id.fishku.consumer.model

object FishPricePredictionData {
    val price = listOf(
        FishPricePrediction(
            "1",
            "Provinsi Naggroe Aceh Darussalam",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "12",
            "12",
            "13",
            "14",
            "14",
            "14",
        ),
        FishPricePrediction(
            "2",
            "Provinsi Sumatera Utara",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "24",
            "32",
            "1",
            "23",
            "12",
            "123",
        ),
        FishPricePrediction(
            "3",
            "Provinsi Sumataera Selatan",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "4",
            "Provinsi Sumatera Barat",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "5",
            "Provinsi Bengkulu",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "6",
            "Provinsi Riau",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "7",
            "Provinsi Kepulauan Riau",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "8",
            "Provinsi Jambi",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "9",
            "Provinsi Lampung",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "10",
            "Provinsi Bangka Belitung",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "11",
            "Provinsi Kalimantan Barat",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "12",
            "Provinsi Kalimantan Timur",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "13",
            "Provinsi Kalimantan Selatan",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "14",
            "Provinsi Kalimantan Tengah",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "15",
            "Provinsi Kalimantan Utara",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "16",
            "Provinsi Banten",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "17",
            "Provinsi DKI Jakarta",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "18",
            "Provinsi Jawa Barat",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "19",
            "Provinsi Jawa Tengah",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "20",
            "Daerah Istimewa Yogyakarta",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "21",
            "Provinsi Jawa Timur",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "22",
            "Provinsi Nusa Tenggara Timur",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "23",
            "Provinsi Nusa Tenggara Barat",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "24",
            "Provinsi Bali",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "25",
            "Provinsi Gorontalo",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "26",
            "Provinsi Sulawesi Barat",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "27",
            "Provinsi Sulawesi Tengah",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "28",
            "Provinsi Sulawesi Utara",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "29",
            "Provinsi Sulawesi Tenggara",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "30",
            "Provinsi Sulawesi Selatan",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "31",
            "Provinsi Maluku Utara",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "32",
            "Provinsi Maluku",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "33",
            "Provinsi Papua Barat",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "34",
            "Provinsi Papua",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "35",
            "Provinsi Papua Tengah",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "36",
            "Provinsi Papua Pegunungan",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "37",
            "Provinsi Papua Selatan",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ),
        FishPricePrediction(
            "38",
            "Provinsi Papua Barat Daya",
            "Ikan Bandeng",
            "Ikan kembung",
            "Ikan Kuniran",
            "Ikan Mujair",
            "Ikan Nila",
            "Ikan Tongkol",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        )
    )
}