package id.fishku.consumer.model

object FishPricePredictionData {
    val price = listOf(
        FishPricePrediction(
            "1",
            "Provinsi Naggroe Aceh Darussalam",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 35.000",
            "Rp. 15.000",
            "Rp. 25.000",
            "Rp. 35.000",
            "Rp. 35.000",
            "Rp. 14.000 - 17.000",
        ),
        FishPricePrediction(
            "2",
            "Provinsi Sumatera Utara",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 36.580",
            "Rp. 44.180",
            "Rp. 35.000",
            "Rp. 35.000",
            "Rp. 35.000",
            "Rp. 35.580",
        ),
        FishPricePrediction(
            "3",
            "Provinsi Sumataera Selatan",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 29.130",
            "Rp. 35.740",
            "Rp. 45.000",
            "Rp. 29.000",
            "Rp. 40.000",
            "Rp. 28.560",
        ),
        FishPricePrediction(
            "4",
            "Provinsi Sumatera Barat",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 33.470",
            "Rp. 47.290",
            "Rp. 30.000",
            "Rp. 40.000",
            "Rp. 36.500",
            "Rp. 39.340",
        ),
        FishPricePrediction(
            "5",
            "Provinsi Bengkulu",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 36.580",
            "Rp. 44.420",
            "Rp. 35.000",
            "Rp. 25.000",
            "Rp. 30.000",
            "Rp. 36.700",
        ),
        FishPricePrediction(
            "6",
            "Provinsi Riau",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 41.000",
            "Rp. 43.390",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 39.730",
        ),
        FishPricePrediction(
            "7",
            "Provinsi Kepulauan Riau",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 41.000",
            "Rp. 43.390",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 39.730",
        ),
        FishPricePrediction(
            "8",
            "Provinsi Jambi",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 32.400",
            "Rp. 37.490",
            "Rp. 30.000",
            "Rp. 40.000",
            "Rp. 30.000",
            "Rp. 31.410",
        ),
        FishPricePrediction(
            "9",
            "Provinsi Lampung",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 29.000",
            "Rp. 34.900",
            "Rp. 30.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 30.200",
        ),
        FishPricePrediction(
            "10",
            "Provinsi Bangka Belitung",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 41.000",
            "Rp. 43.390",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 39.730",
        ),
        FishPricePrediction(
            "11",
            "Provinsi Kalimantan Barat",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 16.000 - 25.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 35.000",
        ),
        FishPricePrediction(
            "12",
            "Provinsi Kalimantan Timur",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 16.000 - 25.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 35.000",
        ),
        FishPricePrediction(
            "13",
            "Provinsi Kalimantan Selatan",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 16.000 - 25.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 35.000",
        ),
        FishPricePrediction(
            "14",
            "Provinsi Kalimantan Tengah",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 16.000 - 25.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 35.000",
        ),
        FishPricePrediction(
            "15",
            "Provinsi Kalimantan Utara",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 16.000 - 25.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 35.000",
        ),
        FishPricePrediction(
            "16",
            "Provinsi Banten",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 34.430",
            "Rp. 39.120",
            "Rp. 30.000",
            "Rp. 27.000",
            "Rp. 40.000",
            "Rp. 34.750",
        ),
        FishPricePrediction(
            "17",
            "Provinsi DKI Jakarta",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 35.520",
            "Rp. 33.250",
            "Rp. 30.000",
            "Rp. 35.000",
            "RP. 40.000",
            "Rp. 33.000",
        ),
        FishPricePrediction(
            "18",
            "Provinsi Jawa Barat",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 19.000 - 21.000",
            "Rp. 39.500",
            "Rp. 35.000",
            "Rp. 28.000",
            "Rp. 40.000",
            "Rp. 37.500",
        ),
        FishPricePrediction(
            "19",
            "Provinsi Jawa Tengah",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 22.000",
            "Rp. 33.200",
            "Rp. 30.000",
            "Rp. 25.000 - 30.000",
            "Rp. 40.000",
            "Rp. 33.500",
        ),
        FishPricePrediction(
            "20",
            "Daerah Istimewa Yogyakarta",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 33.000 - 42.000",
            "Rp. 43.000",
            "Rp. 30.000",
            "Rp. 38.000 - 45.000",
            "Rp. 24.000 - 34.000",
            "Rp. 36.000",
        ),
        FishPricePrediction(
            "21",
            "Provinsi Jawa Timur",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 8.500 - 18.000",
            "Rp. 35.000",
            "Rp. 35.000",
            "Rp. 26.000 - 27.000",
            "Rp. 40.000",
            "Rp. 33.000",
        ),
        FishPricePrediction(
            "22",
            "Provinsi Nusa Tenggara Timur",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 29.000",
            "Rp. 34.300",
            "Rp. 30.000",
            "Rp. 25.000 - 30.000",
            "Rp. 40.000",
            "Rp. 27.500",
        ),
        FishPricePrediction(
            "23",
            "Provinsi Nusa Tenggara Barat",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 29.000",
            "Rp. 34.300",
            "Rp. 30.000",
            "Rp. 25.000 - 30.000",
            "Rp. 40.000",
            "Rp. 27.500",
        ),
        FishPricePrediction(
            "24",
            "Provinsi Bali",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 32.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 32.000",
            "Rp. 45.000",
            "Rp. 32.000",
        ),
        FishPricePrediction(
            "25",
            "Provinsi Gorontalo",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 21.000",
            "Rp. 34.300",
            "Rp. 30.000",
            "Rp. 25.000 - 30.000",
            "Rp. 40.000",
            "Rp. 27.500",
        ),
        FishPricePrediction(
            "26",
            "Provinsi Sulawesi Barat",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 22.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "27",
            "Provinsi Sulawesi Tengah",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 22.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "28",
            "Provinsi Sulawesi Utara",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 22.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "29",
            "Provinsi Sulawesi Tenggara",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 22.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "30",
            "Provinsi Sulawesi Selatan",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 18.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "31",
            "Provinsi Maluku Utara",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 18.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "32",
            "Provinsi Maluku",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 18.000",
            "Rp. 45.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 40.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "33",
            "Provinsi Papua Barat",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 40.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 45.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "34",
            "Provinsi Papua",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 40.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 45.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "35",
            "Provinsi Papua Tengah",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 40.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 45.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "36",
            "Provinsi Papua Pegunungan",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 40.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 45.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "37",
            "Provinsi Papua Selatan",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 40.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 45.000",
            "Rp. 40.000",
        ),
        FishPricePrediction(
            "38",
            "Provinsi Papua Barat Daya",
            "Ikan Bandeng : ",
            "Ikan kembung : ",
            "Ikan Kuniran : ",
            "Ikan Mujair : ",
            "Ikan Nila : ",
            "Ikan Tongkol : ",
            "Rp. 40.000",
            "Rp. 35.000",
            "Rp. 30.000",
            "Rp. 35.000",
            "Rp. 45.000",
            "Rp. 40.000",
        )
    )
}